# Pocket Pantry Android Client Build

trigger:
  branches:
    include:
    - master
  paths:
    include:
      - src/client
      - pipelines/pocket-pantry-android-build.yml
    exclude:
      - infrastructure
      - scripts

pool:
  vmImage: 'windows-latest'

steps:

- script: npm install -g ionic
  displayName: 'Install Ionic'

- script: npm install -g cordova
  displayName: 'Install Cordova'

- script: | 
    cd src/Client
    npm install
  displayName: 'Command: npm install'

- script: | 
    cd src/Client
    ionic cordova build android --prod --release
  displayName: 'Ionic Android Build'

- task: CopyFiles@2
  displayName: Build Output Artifact Copy
  inputs:
    Contents: |
      src/Client/platforms/android/**
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: drop
    ArtifactType: Container
